apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  # Base64 encoded JWT key - replace with: echo -n "your-jwt-key" | base64
  JWT_KEY: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1oZXJl  # Replace this
---
apiVersion: v1
kind: Secret
metadata:
  name: stripe-secret
type: Opaque
data:
  # Base64 encoded Stripe key - replace with: echo -n "sk_test_your_key" | base64
  STRIPE_KEY: c2tfdGVzdF95b3VyX3N0cmlwZV9zZWNyZXRfa2V5X2hlcmU=  # Replace this