apiVersion: v1
kind: Secret
metadata:
  name: stripe-secret
type: Opaque
data:
  # Your Stripe secret key should be base64 encoded
  # Replace 'your-stripe-secret-key-here' with your actual secret key from Stripe dashboard
  # Run: echo -n 'sk_test_your_actual_secret_key' | base64
  STRIPE_KEY: c2tfdGVzdF95b3VyX2FjdHVhbF9zZWNyZXRfa2V5