name: deploy-auth

on:
  push:
    branches:
      - master
    paths:
      - "auth/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set image tag
        id: vars
        run: echo "TAG=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV

      - name: Build Docker image
        run: cd auth && docker build -t rarias1082/auth:${TAG} .

      - name: Login to Docker Hub
        run: docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push image
        run: |
          docker push rarias1082/auth:${TAG}
          docker tag rarias1082/auth:${TAG} rarias1082/auth:latest
          docker push rarias1082/auth:latest
