name: deploy-auth

on:
  push:
    branches:
      - master
    paths:
      - "auth/**"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      KOPS_CLUSTER_NAME: kubevpro.basquiat.app
      KOPS_STATE_STORE: s3://kopsstate1357
      AWS_REGION: us-east-2

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Configure kubectl for Kops cluster
        run: |
          kops export kubecfg --name=${KOPS_CLUSTER_NAME} --state=${KOPS_STATE_STORE}

      - name: Set image tag
        id: vars
        run: echo "TAG=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV

      - name: Build Docker image
        run: cd auth && docker build -t rarias1082/auth:${TAG} .

      - name: Login to Docker Hub
        run: docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push rarias1082/auth:${TAG}
          docker tag rarias1082/auth:${TAG} rarias1082/auth:latest
          docker push rarias1082/auth:latest

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/auth-depl auth=rarias1082/auth:${TAG}
          kubectl rollout status deployment/auth-depl
